version: '3.7'

services:
  github-proxy:
    restart: always
    image: whatwewant/github-proxy:${SERVICE_GITHUB_PROXY_IMAGE_VERSION}
    environment:
      DEBUG: "${SERVICE_GITHUB_PROXY_DEBUG}"
    volumes:
      - type: bind
        source: /etc/localtime
        target: /etc/localtime

networks:
  default:
    external: true
    name: compose-ingress
